<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['pagination_airyo'] = array(
	'full_tag_open'     => '<ul class="pagination">',
	'full_tag_close'    => '</ul>',
	'first_link'        => '&laquo;',
	'first_tag_open'    => '<li>',
	'first_tag_close'   => '</li>',
	'last_link'         => '&raquo;',
	'last_tag_open'     => '<li>',
	'last_tag_close'    => '</li>',
	'next_link'         => '→',
	'next_tag_open'     => '<li>',
	'next_tag_close'    => '</li>',
	'prev_link'         => '←',
	'prev_tag_open'     => '<li>',
	'prev_tag_close'    => '</li>',
	'cur_tag_open'      => '<li class="active"><span>',
	'cur_tag_close'     => '<span class="sr-only">(current)</span></span></li>',
	'num_tag_open'      => '<li>',
	'num_tag_close'     => '</li>',
	'base_url'          => '',
	'total_rows'        => '',
	'uri_segment'       => '',
	'per_page'          => ''
);

$config['pagination'] = array(
	'full_tag_open'     => '<ul class="pagination">',
	'full_tag_close'    => '</ul>',
	'first_link'        => '&laquo;',
	'first_tag_open'    => '<li>',
	'first_tag_close'   => '</li>',
	'last_link'         => '&raquo;',
	'last_tag_open'     => '<li>',
	'last_tag_close'    => '</li>',
	'next_link'         => '→',
	'next_tag_open'     => '<li>',
	'next_tag_close'    => '</li>',
	'prev_link'         => '←',
	'prev_tag_open'     => '<li>',
	'prev_tag_close'    => '</li>',
	'cur_tag_open'      => '<li class="active"><span>',
	'cur_tag_close'     => '<span class="sr-only">(current)</span></span></li>',
	'num_tag_open'      => '<li>',
	'num_tag_close'     => '</li>',
	'base_url'          => '',
	'total_rows'        => '',
	'uri_segment'       => '',
	'per_page'          => ''
);